---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - top
      volumeMounts:
      - name: gluster-volume
        mountPath: "/data"
        readOnly: false
  volumes:
  - name: gluster-volume
    persistentVolumeClaim:
      claimName: glusterfs-pvc
