kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "glusterfs-storageclass"
  resources:
    requests:
      storage: 1Gi
