# 挂载的方式
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: nfs-pvc001
          mountPath: /data/pvc001
          readOnly: false
  volumes:
    - name: nfs-pvc001
      persistentVolumeClaim:
        claimName: pvc001
  restartPolicy: Always
