apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # 只有设置了 该 Class 的 PV 才能被系统选出，井与该 PVC 进行绑定。
  storageClassName: nfs
  # PV 选择条件（Selector）
  selector:
    matchLabels:
      nfs-pv: pv001

